export const CAMPAIGN_DETAIL_ERROR = {
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  ALREADY_CLOSED: 'ALREADY_CLOSED',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  SELECTION_COUNT_EXCEEDED: 'SELECTION_COUNT_EXCEEDED',
  NO_SELECTION: 'NO_SELECTION',
  NO_APPLICANTS: 'NO_APPLICANTS',
  INVALID_STATUS: 'INVALID_STATUS',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export type CampaignDetailErrorCode =
  (typeof CAMPAIGN_DETAIL_ERROR)[keyof typeof CAMPAIGN_DETAIL_ERROR];
